package com.colsevi.dao.inventario.model;

import java.math.BigDecimal;

public class InventarioXMateria {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventario_x_materia.id_inventario
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	private Integer id_inventario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventario_x_materia.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	private Integer id_ingrediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventario_x_materia.lote
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	private Integer lote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventario_x_materia.id_unidad_peso
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	private Integer id_unidad_peso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inventario_x_materia.cantidad
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	private Double cantidad;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventario_x_materia.id_inventario
	 * @return  the value of inventario_x_materia.id_inventario
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public Integer getId_inventario() {
		return id_inventario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventario_x_materia.id_inventario
	 * @param id_inventario  the value for inventario_x_materia.id_inventario
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public void setId_inventario(Integer id_inventario) {
		this.id_inventario = id_inventario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventario_x_materia.id_ingrediente
	 * @return  the value of inventario_x_materia.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public Integer getId_ingrediente() {
		return id_ingrediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventario_x_materia.id_ingrediente
	 * @param id_ingrediente  the value for inventario_x_materia.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public void setId_ingrediente(Integer id_ingrediente) {
		this.id_ingrediente = id_ingrediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventario_x_materia.lote
	 * @return  the value of inventario_x_materia.lote
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public Integer getLote() {
		return lote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventario_x_materia.lote
	 * @param lote  the value for inventario_x_materia.lote
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public void setLote(Integer lote) {
		this.lote = lote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventario_x_materia.id_unidad_peso
	 * @return  the value of inventario_x_materia.id_unidad_peso
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public Integer getId_unidad_peso() {
		return id_unidad_peso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventario_x_materia.id_unidad_peso
	 * @param id_unidad_peso  the value for inventario_x_materia.id_unidad_peso
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public void setId_unidad_peso(Integer id_unidad_peso) {
		this.id_unidad_peso = id_unidad_peso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inventario_x_materia.cantidad
	 * @return  the value of inventario_x_materia.cantidad
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public Double getCantidad() {
		return cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inventario_x_materia.cantidad
	 * @param cantidad  the value for inventario_x_materia.cantidad
	 * @mbg.generated  Fri Apr 28 17:59:30 COT 2017
	 */
	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}
}