package com.colsevi.dao.inventario.model;

import java.util.Date;

public class MovimientoMateria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_materia.id_momivimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    private Integer id_momivimiento_materia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_materia.id_motivo
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    private Integer id_motivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_materia.lote
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    private Integer lote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_materia.id_unidad_peso
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    private Integer id_unidad_peso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_materia.id_establecimiento
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    private Integer id_establecimiento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_materia.cantidad
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    private Double cantidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_materia.fecha_movimiento
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    private Date fecha_movimiento;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_materia.id_momivimiento_materia
     *
     * @return the value of movimiento_materia.id_momivimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public Integer getId_momivimiento_materia() {
        return id_momivimiento_materia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_materia.id_momivimiento_materia
     *
     * @param id_momivimiento_materia the value for movimiento_materia.id_momivimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public void setId_momivimiento_materia(Integer id_momivimiento_materia) {
        this.id_momivimiento_materia = id_momivimiento_materia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_materia.id_motivo
     *
     * @return the value of movimiento_materia.id_motivo
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public Integer getId_motivo() {
        return id_motivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_materia.id_motivo
     *
     * @param id_motivo the value for movimiento_materia.id_motivo
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public void setId_motivo(Integer id_motivo) {
        this.id_motivo = id_motivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_materia.lote
     *
     * @return the value of movimiento_materia.lote
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public Integer getLote() {
        return lote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_materia.lote
     *
     * @param lote the value for movimiento_materia.lote
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public void setLote(Integer lote) {
        this.lote = lote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_materia.id_unidad_peso
     *
     * @return the value of movimiento_materia.id_unidad_peso
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public Integer getId_unidad_peso() {
        return id_unidad_peso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_materia.id_unidad_peso
     *
     * @param id_unidad_peso the value for movimiento_materia.id_unidad_peso
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public void setId_unidad_peso(Integer id_unidad_peso) {
        this.id_unidad_peso = id_unidad_peso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_materia.id_establecimiento
     *
     * @return the value of movimiento_materia.id_establecimiento
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public Integer getId_establecimiento() {
        return id_establecimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_materia.id_establecimiento
     *
     * @param id_establecimiento the value for movimiento_materia.id_establecimiento
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public void setId_establecimiento(Integer id_establecimiento) {
        this.id_establecimiento = id_establecimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_materia.cantidad
     *
     * @return the value of movimiento_materia.cantidad
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public Double getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_materia.cantidad
     *
     * @param cantidad the value for movimiento_materia.cantidad
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_materia.fecha_movimiento
     *
     * @return the value of movimiento_materia.fecha_movimiento
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public Date getFecha_movimiento() {
        return fecha_movimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_materia.fecha_movimiento
     *
     * @param fecha_movimiento the value for movimiento_materia.fecha_movimiento
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    public void setFecha_movimiento(Date fecha_movimiento) {
        this.fecha_movimiento = fecha_movimiento;
    }
}