package com.colsevi.dao.inventario.model;

public class MovimientoInventario extends MovimientoInventarioKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_inventario.id_establecimiento
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    private Integer id_establecimiento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_inventario.id_producto
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    private Integer id_producto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_inventario.disponible
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    private Integer disponible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movimiento_inventario.compromiso
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    private Integer compromiso;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_inventario.id_establecimiento
     *
     * @return the value of movimiento_inventario.id_establecimiento
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public Integer getId_establecimiento() {
        return id_establecimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_inventario.id_establecimiento
     *
     * @param id_establecimiento the value for movimiento_inventario.id_establecimiento
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public void setId_establecimiento(Integer id_establecimiento) {
        this.id_establecimiento = id_establecimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_inventario.id_producto
     *
     * @return the value of movimiento_inventario.id_producto
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public Integer getId_producto() {
        return id_producto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_inventario.id_producto
     *
     * @param id_producto the value for movimiento_inventario.id_producto
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public void setId_producto(Integer id_producto) {
        this.id_producto = id_producto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_inventario.disponible
     *
     * @return the value of movimiento_inventario.disponible
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public Integer getDisponible() {
        return disponible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_inventario.disponible
     *
     * @param disponible the value for movimiento_inventario.disponible
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public void setDisponible(Integer disponible) {
        this.disponible = disponible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movimiento_inventario.compromiso
     *
     * @return the value of movimiento_inventario.compromiso
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public Integer getCompromiso() {
        return compromiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movimiento_inventario.compromiso
     *
     * @param compromiso the value for movimiento_inventario.compromiso
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    public void setCompromiso(Integer compromiso) {
        this.compromiso = compromiso;
    }
}