package com.colsevi.dao.catalogo.map;

import com.colsevi.dao.catalogo.model.Catalogo;
import com.colsevi.dao.catalogo.model.CatalogoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatalogoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int countByExample(CatalogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int deleteByExample(CatalogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int deleteByPrimaryKey(Integer id_catalogo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int insert(Catalogo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int insertSelective(Catalogo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    List<Catalogo> selectByExample(CatalogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    Catalogo selectByPrimaryKey(Integer id_catalogo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int updateByExampleSelective(@Param("record") Catalogo record, @Param("example") CatalogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int updateByExample(@Param("record") Catalogo record, @Param("example") CatalogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int updateByPrimaryKeySelective(Catalogo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogo
     *
     * @mbggenerated Thu Mar 10 16:31:50 COT 2016
     */
    int updateByPrimaryKey(Catalogo record);
}