package com.colsevi.dao.general.model;

public class Configuracion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column configuracion.codigo
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	private String codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column configuracion.valor
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	private String valor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column configuracion.descripcion
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column configuracion.codigo
	 * @return  the value of configuracion.codigo
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column configuracion.codigo
	 * @param codigo  the value for configuracion.codigo
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column configuracion.valor
	 * @return  the value of configuracion.valor
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	public String getValor() {
		return valor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column configuracion.valor
	 * @param valor  the value for configuracion.valor
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	public void setValor(String valor) {
		this.valor = valor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column configuracion.descripcion
	 * @return  the value of configuracion.descripcion
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column configuracion.descripcion
	 * @param descripcion  the value for configuracion.descripcion
	 * @mbg.generated  Fri Apr 28 18:12:49 COT 2017
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}