package com.colsevi.dao.general.model;

public class GeneralLocal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_local.id_local
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    private Integer id_local;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_local.nombre
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general_local.descripcion
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_local.id_local
     *
     * @return the value of general_local.id_local
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    public Integer getId_local() {
        return id_local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_local.id_local
     *
     * @param id_local the value for general_local.id_local
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    public void setId_local(Integer id_local) {
        this.id_local = id_local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_local.nombre
     *
     * @return the value of general_local.nombre
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_local.nombre
     *
     * @param nombre the value for general_local.nombre
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general_local.descripcion
     *
     * @return the value of general_local.descripcion
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general_local.descripcion
     *
     * @param descripcion the value for general_local.descripcion
     *
     * @mbggenerated Tue Oct 27 21:04:31 COT 2015
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}