package com.colsevi.dao.general.model;

import java.util.ArrayList;
import java.util.List;

public class MensajeriaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public MensajeriaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodigoIsNull() {
            addCriterion("codigo is null");
            return (Criteria) this;
        }

        public Criteria andCodigoIsNotNull() {
            addCriterion("codigo is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoEqualTo(String value) {
            addCriterion("codigo =", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotEqualTo(String value) {
            addCriterion("codigo <>", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoGreaterThan(String value) {
            addCriterion("codigo >", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo >=", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoLessThan(String value) {
            addCriterion("codigo <", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoLessThanOrEqualTo(String value) {
            addCriterion("codigo <=", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoLike(String value) {
            addCriterion("codigo like", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotLike(String value) {
            addCriterion("codigo not like", value, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoIn(List<String> values) {
            addCriterion("codigo in", values, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotIn(List<String> values) {
            addCriterion("codigo not in", values, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoBetween(String value1, String value2) {
            addCriterion("codigo between", value1, value2, "codigo");
            return (Criteria) this;
        }

        public Criteria andCodigoNotBetween(String value1, String value2) {
            addCriterion("codigo not between", value1, value2, "codigo");
            return (Criteria) this;
        }

        public Criteria andAsuntoIsNull() {
            addCriterion("asunto is null");
            return (Criteria) this;
        }

        public Criteria andAsuntoIsNotNull() {
            addCriterion("asunto is not null");
            return (Criteria) this;
        }

        public Criteria andAsuntoEqualTo(String value) {
            addCriterion("asunto =", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoNotEqualTo(String value) {
            addCriterion("asunto <>", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoGreaterThan(String value) {
            addCriterion("asunto >", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoGreaterThanOrEqualTo(String value) {
            addCriterion("asunto >=", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoLessThan(String value) {
            addCriterion("asunto <", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoLessThanOrEqualTo(String value) {
            addCriterion("asunto <=", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoLike(String value) {
            addCriterion("asunto like", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoNotLike(String value) {
            addCriterion("asunto not like", value, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoIn(List<String> values) {
            addCriterion("asunto in", values, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoNotIn(List<String> values) {
            addCriterion("asunto not in", values, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoBetween(String value1, String value2) {
            addCriterion("asunto between", value1, value2, "asunto");
            return (Criteria) this;
        }

        public Criteria andAsuntoNotBetween(String value1, String value2) {
            addCriterion("asunto not between", value1, value2, "asunto");
            return (Criteria) this;
        }

        public Criteria andMensajeIsNull() {
            addCriterion("mensaje is null");
            return (Criteria) this;
        }

        public Criteria andMensajeIsNotNull() {
            addCriterion("mensaje is not null");
            return (Criteria) this;
        }

        public Criteria andMensajeEqualTo(String value) {
            addCriterion("mensaje =", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotEqualTo(String value) {
            addCriterion("mensaje <>", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeGreaterThan(String value) {
            addCriterion("mensaje >", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeGreaterThanOrEqualTo(String value) {
            addCriterion("mensaje >=", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeLessThan(String value) {
            addCriterion("mensaje <", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeLessThanOrEqualTo(String value) {
            addCriterion("mensaje <=", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeLike(String value) {
            addCriterion("mensaje like", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotLike(String value) {
            addCriterion("mensaje not like", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeIn(List<String> values) {
            addCriterion("mensaje in", values, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotIn(List<String> values) {
            addCriterion("mensaje not in", values, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeBetween(String value1, String value2) {
            addCriterion("mensaje between", value1, value2, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotBetween(String value1, String value2) {
            addCriterion("mensaje not between", value1, value2, "mensaje");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mensajeria
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 02 16:45:48 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mensajeria
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}