package com.colsevi.dao.general.model;

public class Mensajeria {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mensajeria.codigo
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    private String codigo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mensajeria.asunto
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    private String asunto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mensajeria.mensaje
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    private String mensaje;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mensajeria.codigo
     *
     * @return the value of mensajeria.codigo
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mensajeria.codigo
     *
     * @param codigo the value for mensajeria.codigo
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mensajeria.asunto
     *
     * @return the value of mensajeria.asunto
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public String getAsunto() {
        return asunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mensajeria.asunto
     *
     * @param asunto the value for mensajeria.asunto
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mensajeria.mensaje
     *
     * @return the value of mensajeria.mensaje
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mensajeria.mensaje
     *
     * @param mensaje the value for mensajeria.mensaje
     *
     * @mbg.generated Sun Jul 02 16:45:48 COT 2017
     */
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
}