package com.colsevi.dao.general.model;

public class Motivo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column motivo.id_motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	private Integer id_motivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column motivo.nombre
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	private String nombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column motivo.id_motivo
	 * @return  the value of motivo.id_motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	public Integer getId_motivo() {
		return id_motivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column motivo.id_motivo
	 * @param id_motivo  the value for motivo.id_motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	public void setId_motivo(Integer id_motivo) {
		this.id_motivo = id_motivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column motivo.nombre
	 * @return  the value of motivo.nombre
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column motivo.nombre
	 * @param nombre  the value for motivo.nombre
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}