package com.colsevi.dao.general.model;

public class TipoTelefono {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_telefono.id_tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	private Integer id_tipo_telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_telefono.nombre
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_telefono.descripcion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_telefono.id_tipo_telefono
	 * @return  the value of tipo_telefono.id_tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	public Integer getId_tipo_telefono() {
		return id_tipo_telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_telefono.id_tipo_telefono
	 * @param id_tipo_telefono  the value for tipo_telefono.id_tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	public void setId_tipo_telefono(Integer id_tipo_telefono) {
		this.id_tipo_telefono = id_tipo_telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_telefono.nombre
	 * @return  the value of tipo_telefono.nombre
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_telefono.nombre
	 * @param nombre  the value for tipo_telefono.nombre
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_telefono.descripcion
	 * @return  the value of tipo_telefono.descripcion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_telefono.descripcion
	 * @param descripcion  the value for tipo_telefono.descripcion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}