package com.colsevi.dao.general.model;

public class UnidadPeso {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidad_peso.id_unidad_peso
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    private Integer id_unidad_peso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidad_peso.nombre
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidad_peso.descripcion
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidad_peso.id_unidad_peso
     *
     * @return the value of unidad_peso.id_unidad_peso
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    public Integer getId_unidad_peso() {
        return id_unidad_peso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidad_peso.id_unidad_peso
     *
     * @param id_unidad_peso the value for unidad_peso.id_unidad_peso
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    public void setId_unidad_peso(Integer id_unidad_peso) {
        this.id_unidad_peso = id_unidad_peso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidad_peso.nombre
     *
     * @return the value of unidad_peso.nombre
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidad_peso.nombre
     *
     * @param nombre the value for unidad_peso.nombre
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidad_peso.descripcion
     *
     * @return the value of unidad_peso.descripcion
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidad_peso.descripcion
     *
     * @param descripcion the value for unidad_peso.descripcion
     *
     * @mbggenerated Tue Apr 12 16:26:48 COT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}