package com.colsevi.dao.ingrediente.model;

public class Ingrediente {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ingrediente.id_ingrediente
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    private Integer id_ingrediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ingrediente.nombre
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ingrediente.descripcion
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ingrediente.id_ingrediente
     *
     * @return the value of ingrediente.id_ingrediente
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    public Integer getId_ingrediente() {
        return id_ingrediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ingrediente.id_ingrediente
     *
     * @param id_ingrediente the value for ingrediente.id_ingrediente
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    public void setId_ingrediente(Integer id_ingrediente) {
        this.id_ingrediente = id_ingrediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ingrediente.nombre
     *
     * @return the value of ingrediente.nombre
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ingrediente.nombre
     *
     * @param nombre the value for ingrediente.nombre
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ingrediente.descripcion
     *
     * @return the value of ingrediente.descripcion
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ingrediente.descripcion
     *
     * @param descripcion the value for ingrediente.descripcion
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}