package com.colsevi.dao.catalogo.model;

public class CatalogoXProductoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catalogo_x_producto.id_catalogo
	 * @mbg.generated  Fri Apr 28 17:51:33 COT 2017
	 */
	private Integer id_catalogo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column catalogo_x_producto.id_producto
	 * @mbg.generated  Fri Apr 28 17:51:33 COT 2017
	 */
	private Integer id_producto;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catalogo_x_producto.id_catalogo
	 * @return  the value of catalogo_x_producto.id_catalogo
	 * @mbg.generated  Fri Apr 28 17:51:33 COT 2017
	 */
	public Integer getId_catalogo() {
		return id_catalogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catalogo_x_producto.id_catalogo
	 * @param id_catalogo  the value for catalogo_x_producto.id_catalogo
	 * @mbg.generated  Fri Apr 28 17:51:33 COT 2017
	 */
	public void setId_catalogo(Integer id_catalogo) {
		this.id_catalogo = id_catalogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column catalogo_x_producto.id_producto
	 * @return  the value of catalogo_x_producto.id_producto
	 * @mbg.generated  Fri Apr 28 17:51:33 COT 2017
	 */
	public Integer getId_producto() {
		return id_producto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column catalogo_x_producto.id_producto
	 * @param id_producto  the value for catalogo_x_producto.id_producto
	 * @mbg.generated  Fri Apr 28 17:51:33 COT 2017
	 */
	public void setId_producto(Integer id_producto) {
		this.id_producto = id_producto;
	}
}