package com.colsevi.dao.pago.model;

import java.math.BigDecimal;
import java.util.Date;

public class Pago {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pago.id_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    private Integer id_pago;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pago.id_categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    private Integer id_categoria_modulo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pago.documento
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    private Integer documento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pago.pendiente
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    private BigDecimal pendiente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pago.fecha
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    private Date fecha;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pago.id_pago
     *
     * @return the value of pago.id_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public Integer getId_pago() {
        return id_pago;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pago.id_pago
     *
     * @param id_pago the value for pago.id_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public void setId_pago(Integer id_pago) {
        this.id_pago = id_pago;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pago.id_categoria_modulo
     *
     * @return the value of pago.id_categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public Integer getId_categoria_modulo() {
        return id_categoria_modulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pago.id_categoria_modulo
     *
     * @param id_categoria_modulo the value for pago.id_categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public void setId_categoria_modulo(Integer id_categoria_modulo) {
        this.id_categoria_modulo = id_categoria_modulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pago.documento
     *
     * @return the value of pago.documento
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public Integer getDocumento() {
        return documento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pago.documento
     *
     * @param documento the value for pago.documento
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public void setDocumento(Integer documento) {
        this.documento = documento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pago.pendiente
     *
     * @return the value of pago.pendiente
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public BigDecimal getPendiente() {
        return pendiente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pago.pendiente
     *
     * @param pendiente the value for pago.pendiente
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public void setPendiente(BigDecimal pendiente) {
        this.pendiente = pendiente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pago.fecha
     *
     * @return the value of pago.fecha
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pago.fecha
     *
     * @param fecha the value for pago.fecha
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}