package com.colsevi.dao.deuda.model;

import java.math.BigDecimal;
import java.util.Date;

public class DeudaProveedor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deuda_proveedor.id_deuda_proveedor
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    private Integer id_deuda_proveedor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deuda_proveedor.id_compra
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    private Integer id_compra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deuda_proveedor.pendiente
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    private BigDecimal pendiente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deuda_proveedor.fecha_deuda
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    private Date fecha_deuda;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deuda_proveedor.observacion
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    private String observacion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deuda_proveedor.id_deuda_proveedor
     *
     * @return the value of deuda_proveedor.id_deuda_proveedor
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public Integer getId_deuda_proveedor() {
        return id_deuda_proveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deuda_proveedor.id_deuda_proveedor
     *
     * @param id_deuda_proveedor the value for deuda_proveedor.id_deuda_proveedor
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public void setId_deuda_proveedor(Integer id_deuda_proveedor) {
        this.id_deuda_proveedor = id_deuda_proveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deuda_proveedor.id_compra
     *
     * @return the value of deuda_proveedor.id_compra
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public Integer getId_compra() {
        return id_compra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deuda_proveedor.id_compra
     *
     * @param id_compra the value for deuda_proveedor.id_compra
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public void setId_compra(Integer id_compra) {
        this.id_compra = id_compra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deuda_proveedor.pendiente
     *
     * @return the value of deuda_proveedor.pendiente
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public BigDecimal getPendiente() {
        return pendiente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deuda_proveedor.pendiente
     *
     * @param pendiente the value for deuda_proveedor.pendiente
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public void setPendiente(BigDecimal pendiente) {
        this.pendiente = pendiente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deuda_proveedor.fecha_deuda
     *
     * @return the value of deuda_proveedor.fecha_deuda
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public Date getFecha_deuda() {
        return fecha_deuda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deuda_proveedor.fecha_deuda
     *
     * @param fecha_deuda the value for deuda_proveedor.fecha_deuda
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public void setFecha_deuda(Date fecha_deuda) {
        this.fecha_deuda = fecha_deuda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deuda_proveedor.observacion
     *
     * @return the value of deuda_proveedor.observacion
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public String getObservacion() {
        return observacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deuda_proveedor.observacion
     *
     * @param observacion the value for deuda_proveedor.observacion
     *
     * @mbggenerated Tue Apr 12 16:30:54 COT 2016
     */
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
}