package com.colsevi.dao.producto.map;

import com.colsevi.dao.producto.model.DificultadReceta;
import com.colsevi.dao.producto.model.DificultadRecetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DificultadRecetaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int countByExample(DificultadRecetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int deleteByExample(DificultadRecetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int deleteByPrimaryKey(Integer id_dificultad_receta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int insert(DificultadReceta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int insertSelective(DificultadReceta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	List<DificultadReceta> selectByExample(DificultadRecetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	DificultadReceta selectByPrimaryKey(Integer id_dificultad_receta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int updateByExampleSelective(@Param("record") DificultadReceta record,
			@Param("example") DificultadRecetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int updateByExample(@Param("record") DificultadReceta record, @Param("example") DificultadRecetaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int updateByPrimaryKeySelective(DificultadReceta record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dificultad_receta
	 * @mbggenerated  Fri Apr 15 20:34:25 COT 2016
	 */
	int updateByPrimaryKey(DificultadReceta record);
}