package com.colsevi.dao.producto.map;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.colsevi.dao.producto.model.Ingrediente;
import com.colsevi.dao.producto.model.IngredienteExample;

public interface IngredienteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	long countByExample(IngredienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int deleteByExample(IngredienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_ingrediente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int insert(Ingrediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int insertSelective(Ingrediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	List<Ingrediente> selectByExample(IngredienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	Ingrediente selectByPrimaryKey(Integer id_ingrediente);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Ingrediente record, @Param("example") IngredienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int updateByExample(@Param("record") Ingrediente record, @Param("example") IngredienteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int updateByPrimaryKeySelective(Ingrediente record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente
	 * @mbg.generated  Fri Apr 28 17:41:01 COT 2017
	 */
	int updateByPrimaryKey(Ingrediente record);

	List<Map<String, Object>> SelectAutocomplete(Map<String, Object> map);
}