package com.colsevi.dao.producto.map;

import com.colsevi.dao.producto.model.IngredienteXProductoExample;
import com.colsevi.dao.producto.model.IngredienteXProductoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IngredienteXProductoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	int countByExample(IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	int deleteByExample(IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	int deleteByPrimaryKey(IngredienteXProductoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	int insert(IngredienteXProductoKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	int insertSelective(IngredienteXProductoKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	List<IngredienteXProductoKey> selectByExample(IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	int updateByExampleSelective(@Param("record") IngredienteXProductoKey record,
			@Param("example") IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbggenerated  Thu Mar 10 16:30:53 COT 2016
	 */
	int updateByExample(@Param("record") IngredienteXProductoKey record,
			@Param("example") IngredienteXProductoExample example);
}