package com.colsevi.dao.producto.map;

import com.colsevi.dao.producto.model.IngredienteXProductoExample;
import com.colsevi.dao.producto.model.IngredienteXProductoKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import com.colsevi.dao.producto.model.IngredienteXProducto;

public interface IngredienteXProductoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	long countByExample(IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int deleteByExample(IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int deleteByPrimaryKey(IngredienteXProductoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int insert(IngredienteXProducto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int insertSelective(IngredienteXProducto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	List<IngredienteXProducto> selectByExample(IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	IngredienteXProducto selectByPrimaryKey(IngredienteXProductoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByExampleSelective(@Param("record") IngredienteXProducto record,
			@Param("example") IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByExample(@Param("record") IngredienteXProducto record,
			@Param("example") IngredienteXProductoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByPrimaryKeySelective(IngredienteXProducto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingrediente_x_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByPrimaryKey(IngredienteXProducto record);

	List<Map<String, Object>> SelectDataView(Map<String, Object> map);
}