package com.colsevi.dao.producto.map;

import com.colsevi.dao.producto.model.PlatoXTipoProducto;
import com.colsevi.dao.producto.model.PlatoXTipoProductoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatoXTipoProductoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plato_x_tipo_producto
     *
     * @mbg.generated Sat Jun 03 15:19:42 COT 2017
     */
    long countByExample(PlatoXTipoProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plato_x_tipo_producto
     *
     * @mbg.generated Sat Jun 03 15:19:42 COT 2017
     */
    int deleteByExample(PlatoXTipoProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plato_x_tipo_producto
     *
     * @mbg.generated Sat Jun 03 15:19:42 COT 2017
     */
    int insert(PlatoXTipoProducto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plato_x_tipo_producto
     *
     * @mbg.generated Sat Jun 03 15:19:42 COT 2017
     */
    int insertSelective(PlatoXTipoProducto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plato_x_tipo_producto
     *
     * @mbg.generated Sat Jun 03 15:19:42 COT 2017
     */
    List<PlatoXTipoProducto> selectByExample(PlatoXTipoProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plato_x_tipo_producto
     *
     * @mbg.generated Sat Jun 03 15:19:42 COT 2017
     */
    int updateByExampleSelective(@Param("record") PlatoXTipoProducto record, @Param("example") PlatoXTipoProductoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plato_x_tipo_producto
     *
     * @mbg.generated Sat Jun 03 15:19:42 COT 2017
     */
    int updateByExample(@Param("record") PlatoXTipoProducto record, @Param("example") PlatoXTipoProductoExample example);
}