package com.colsevi.dao.producto.map;

import com.colsevi.dao.producto.model.PreparacionReceta;
import com.colsevi.dao.producto.model.PreparacionRecetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreparacionRecetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int countByExample(PreparacionRecetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int deleteByExample(PreparacionRecetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int deleteByPrimaryKey(Integer id_preparacion_receta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int insert(PreparacionReceta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int insertSelective(PreparacionReceta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    List<PreparacionReceta> selectByExample(PreparacionRecetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    PreparacionReceta selectByPrimaryKey(Integer id_preparacion_receta);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int updateByExampleSelective(@Param("record") PreparacionReceta record, @Param("example") PreparacionRecetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int updateByExample(@Param("record") PreparacionReceta record, @Param("example") PreparacionRecetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int updateByPrimaryKeySelective(PreparacionReceta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preparacion_receta
     *
     * @mbggenerated Tue Apr 12 16:33:50 COT 2016
     */
    int updateByPrimaryKey(PreparacionReceta record);
}