package com.colsevi.dao.producto.map;

import com.colsevi.dao.producto.model.Producto;
import com.colsevi.dao.producto.model.ProductoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ProductoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	long countByExample(ProductoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int deleteByExample(ProductoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_producto);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int insert(Producto record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int insertSelective(Producto record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	List<Producto> selectByExample(ProductoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	Producto selectByPrimaryKey(Integer id_producto);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Producto record, @Param("example") ProductoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByExample(@Param("record") Producto record, @Param("example") ProductoExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByPrimaryKeySelective(Producto record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByPrimaryKey(Producto record);
	List<Map<String, Object>> SelectAutocomplete(Map<String, Object> map);
	List<Map<String, Object>> ProdInCatalog(Map<String, Object> map);
	List<Map<String, Object>> ListaCatalogoPosibleProducto(Map<String, Object> map);
}