package com.colsevi.dao.producto.map;

import com.colsevi.dao.producto.model.Receta;
import com.colsevi.dao.producto.model.RecetaExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RecetaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	long countByExample(RecetaExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int deleteByExample(RecetaExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_receta);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int insert(Receta record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int insertSelective(Receta record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	List<Receta> selectByExample(RecetaExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	Receta selectByPrimaryKey(Integer id_receta);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Receta record, @Param("example") RecetaExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByExample(@Param("record") Receta record, @Param("example") RecetaExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByPrimaryKeySelective(Receta record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	int updateByPrimaryKey(Receta record);
	List<Map<String, Object>> SelectDataView(Map<String, Object> map);
	int CountDataView(Map<String, Object> map);
}