package com.colsevi.dao.usuario.map;

import com.colsevi.dao.usuario.model.Establecimiento;
import com.colsevi.dao.usuario.model.EstablecimientoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EstablecimientoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int countByExample(EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int deleteByExample(EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int deleteByPrimaryKey(Integer id_establecimiento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int insert(Establecimiento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int insertSelective(Establecimiento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	List<Establecimiento> selectByExample(EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	Establecimiento selectByPrimaryKey(Integer id_establecimiento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int updateByExampleSelective(@Param("record") Establecimiento record,
			@Param("example") EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int updateByExample(@Param("record") Establecimiento record, @Param("example") EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int updateByPrimaryKeySelective(Establecimiento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 17 12:04:38 COT 2016
	 */
	int updateByPrimaryKey(Establecimiento record);
}