package com.colsevi.dao.usuario.map;

import com.colsevi.dao.usuario.model.PaginaXRolExample;
import com.colsevi.dao.usuario.model.PaginaXRolKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaginaXRolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    int countByExample(PaginaXRolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    int deleteByExample(PaginaXRolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    int deleteByPrimaryKey(PaginaXRolKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    int insert(PaginaXRolKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    int insertSelective(PaginaXRolKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    List<PaginaXRolKey> selectByExample(PaginaXRolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    int updateByExampleSelective(@Param("record") PaginaXRolKey record, @Param("example") PaginaXRolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagina_x_rol
     *
     * @mbggenerated Fri Dec 04 22:44:11 COT 2015
     */
    int updateByExample(@Param("record") PaginaXRolKey record, @Param("example") PaginaXRolExample example);
}