package com.colsevi.dao.usuario.map;

import com.colsevi.dao.usuario.model.Rol;
import com.colsevi.dao.usuario.model.RolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	long countByExample(RolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int deleteByExample(RolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_rol);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int insert(Rol record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int insertSelective(Rol record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	List<Rol> selectByExample(RolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	Rol selectByPrimaryKey(Integer id_rol);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Rol record, @Param("example") RolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int updateByExample(@Param("record") Rol record, @Param("example") RolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int updateByPrimaryKeySelective(Rol record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rol
	 * @mbg.generated  Fri Apr 28 17:27:38 COT 2017
	 */
	int updateByPrimaryKey(Rol record);
}