package com.colsevi.dao.usuario.map;

import com.colsevi.dao.usuario.model.Usuario;
import com.colsevi.dao.usuario.model.UsuarioExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	long countByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int deleteByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_usuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int insert(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int insertSelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	List<Usuario> selectByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	Usuario selectByPrimaryKey(Integer id_usuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int updateByPrimaryKeySelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbg.generated  Fri Apr 28 17:28:10 COT 2017
	 */
	int updateByPrimaryKey(Usuario record);

	List<Map<String, Object>> SelectAutocomplete(Map<String, Object> map);
}