package com.colsevi.dao.usuario.map;

import com.colsevi.dao.usuario.model.Usuario;
import com.colsevi.dao.usuario.model.UsuarioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int countByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int deleteByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int deleteByPrimaryKey(Integer id_usuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int insert(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int insertSelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	List<Usuario> selectByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	Usuario selectByPrimaryKey(Integer id_usuario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int updateByExampleSelective(@Param("record") Usuario record,
			@Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int updateByExample(@Param("record") Usuario record,
			@Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int updateByPrimaryKeySelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	int updateByPrimaryKey(Usuario record);
}