package com.colsevi.dao.caja.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CierreCajaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public CierreCajaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andId_cierre_cajaIsNull() {
            addCriterion("id_cierre_caja is null");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaIsNotNull() {
            addCriterion("id_cierre_caja is not null");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaEqualTo(Integer value) {
            addCriterion("id_cierre_caja =", value, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaNotEqualTo(Integer value) {
            addCriterion("id_cierre_caja <>", value, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaGreaterThan(Integer value) {
            addCriterion("id_cierre_caja >", value, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_cierre_caja >=", value, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaLessThan(Integer value) {
            addCriterion("id_cierre_caja <", value, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaLessThanOrEqualTo(Integer value) {
            addCriterion("id_cierre_caja <=", value, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaIn(List<Integer> values) {
            addCriterion("id_cierre_caja in", values, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaNotIn(List<Integer> values) {
            addCriterion("id_cierre_caja not in", values, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaBetween(Integer value1, Integer value2) {
            addCriterion("id_cierre_caja between", value1, value2, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_cierre_cajaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_cierre_caja not between", value1, value2, "id_cierre_caja");
            return (Criteria) this;
        }

        public Criteria andId_personaIsNull() {
            addCriterion("id_persona is null");
            return (Criteria) this;
        }

        public Criteria andId_personaIsNotNull() {
            addCriterion("id_persona is not null");
            return (Criteria) this;
        }

        public Criteria andId_personaEqualTo(Integer value) {
            addCriterion("id_persona =", value, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaNotEqualTo(Integer value) {
            addCriterion("id_persona <>", value, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaGreaterThan(Integer value) {
            addCriterion("id_persona >", value, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_persona >=", value, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaLessThan(Integer value) {
            addCriterion("id_persona <", value, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaLessThanOrEqualTo(Integer value) {
            addCriterion("id_persona <=", value, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaIn(List<Integer> values) {
            addCriterion("id_persona in", values, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaNotIn(List<Integer> values) {
            addCriterion("id_persona not in", values, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaBetween(Integer value1, Integer value2) {
            addCriterion("id_persona between", value1, value2, "id_persona");
            return (Criteria) this;
        }

        public Criteria andId_personaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_persona not between", value1, value2, "id_persona");
            return (Criteria) this;
        }

        public Criteria andMensajeIsNull() {
            addCriterion("mensaje is null");
            return (Criteria) this;
        }

        public Criteria andMensajeIsNotNull() {
            addCriterion("mensaje is not null");
            return (Criteria) this;
        }

        public Criteria andMensajeEqualTo(String value) {
            addCriterion("mensaje =", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotEqualTo(String value) {
            addCriterion("mensaje <>", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeGreaterThan(String value) {
            addCriterion("mensaje >", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeGreaterThanOrEqualTo(String value) {
            addCriterion("mensaje >=", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeLessThan(String value) {
            addCriterion("mensaje <", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeLessThanOrEqualTo(String value) {
            addCriterion("mensaje <=", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeLike(String value) {
            addCriterion("mensaje like", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotLike(String value) {
            addCriterion("mensaje not like", value, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeIn(List<String> values) {
            addCriterion("mensaje in", values, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotIn(List<String> values) {
            addCriterion("mensaje not in", values, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeBetween(String value1, String value2) {
            addCriterion("mensaje between", value1, value2, "mensaje");
            return (Criteria) this;
        }

        public Criteria andMensajeNotBetween(String value1, String value2) {
            addCriterion("mensaje not between", value1, value2, "mensaje");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionIsNull() {
            addCriterion("fecha_ejecucion is null");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionIsNotNull() {
            addCriterion("fecha_ejecucion is not null");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionEqualTo(Date value) {
            addCriterion("fecha_ejecucion =", value, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionNotEqualTo(Date value) {
            addCriterion("fecha_ejecucion <>", value, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionGreaterThan(Date value) {
            addCriterion("fecha_ejecucion >", value, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_ejecucion >=", value, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionLessThan(Date value) {
            addCriterion("fecha_ejecucion <", value, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionLessThanOrEqualTo(Date value) {
            addCriterion("fecha_ejecucion <=", value, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionIn(List<Date> values) {
            addCriterion("fecha_ejecucion in", values, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionNotIn(List<Date> values) {
            addCriterion("fecha_ejecucion not in", values, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionBetween(Date value1, Date value2) {
            addCriterion("fecha_ejecucion between", value1, value2, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_ejecucionNotBetween(Date value1, Date value2) {
            addCriterion("fecha_ejecucion not between", value1, value2, "fecha_ejecucion");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreIsNull() {
            addCriterion("fecha_cierre is null");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreIsNotNull() {
            addCriterion("fecha_cierre is not null");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreEqualTo(Date value) {
            addCriterion("fecha_cierre =", value, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreNotEqualTo(Date value) {
            addCriterion("fecha_cierre <>", value, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreGreaterThan(Date value) {
            addCriterion("fecha_cierre >", value, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_cierre >=", value, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreLessThan(Date value) {
            addCriterion("fecha_cierre <", value, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreLessThanOrEqualTo(Date value) {
            addCriterion("fecha_cierre <=", value, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreIn(List<Date> values) {
            addCriterion("fecha_cierre in", values, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreNotIn(List<Date> values) {
            addCriterion("fecha_cierre not in", values, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreBetween(Date value1, Date value2) {
            addCriterion("fecha_cierre between", value1, value2, "fecha_cierre");
            return (Criteria) this;
        }

        public Criteria andFecha_cierreNotBetween(Date value1, Date value2) {
            addCriterion("fecha_cierre not between", value1, value2, "fecha_cierre");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cierre_caja
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 26 19:26:30 COT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cierre_caja
     *
     * @mbggenerated Tue Apr 26 19:26:30 COT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}