package com.colsevi.dao.proveedor.map;

import com.colsevi.dao.proveedor.model.CompraProveedor;
import com.colsevi.dao.proveedor.model.CompraProveedorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CompraProveedorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	long countByExample(CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int deleteByExample(CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_compra_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int insert(CompraProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int insertSelective(CompraProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	List<CompraProveedor> selectByExample(CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	CompraProveedor selectByPrimaryKey(Integer id_compra_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByExampleSelective(@Param("record") CompraProveedor record,
			@Param("example") CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByExample(@Param("record") CompraProveedor record, @Param("example") CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByPrimaryKeySelective(CompraProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByPrimaryKey(CompraProveedor record);

	int countCambiosDetalleCompra(Map<String, Object> mapa);
	
    List<Map<String, Object>> TablaCompras(Map<String, Object> mapa);
    int CountTablaCompras(Map<String, Object> mapa);
    List<Map<String, Object>> compraEstablecimientoDiario(Map<String, Object> mapa);
    
	
}