package com.colsevi.dao.proveedor.map;

import com.colsevi.dao.proveedor.model.CompraProveedor;
import com.colsevi.dao.proveedor.model.CompraProveedorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompraProveedorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int countByExample(CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int deleteByExample(CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int deleteByPrimaryKey(Integer id_compra_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int insert(CompraProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int insertSelective(CompraProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	List<CompraProveedor> selectByExample(CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	CompraProveedor selectByPrimaryKey(Integer id_compra_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int updateByExampleSelective(@Param("record") CompraProveedor record,
			@Param("example") CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int updateByExample(@Param("record") CompraProveedor record, @Param("example") CompraProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int updateByPrimaryKeySelective(CompraProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table compra_proveedor
	 * @mbggenerated  Tue Oct 18 21:53:49 COT 2016
	 */
	int updateByPrimaryKey(CompraProveedor record);
}