package com.colsevi.dao.proveedor.map;

import com.colsevi.dao.proveedor.model.Proveedor;
import com.colsevi.dao.proveedor.model.ProveedorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ProveedorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	long countByExample(ProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int deleteByExample(ProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int insert(Proveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int insertSelective(Proveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	List<Proveedor> selectByExample(ProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	Proveedor selectByPrimaryKey(Integer id_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Proveedor record, @Param("example") ProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByExample(@Param("record") Proveedor record, @Param("example") ProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByPrimaryKeySelective(Proveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	int updateByPrimaryKey(Proveedor record);

	List<Map<String, Object>> SelectAutocomplete(Map<String, Object> map);
}