package com.colsevi.dao.pago.map;

import com.colsevi.dao.pago.model.DetallePago;
import com.colsevi.dao.pago.model.DetallePagoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetallePagoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int countByExample(DetallePagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int deleteByExample(DetallePagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int deleteByPrimaryKey(Integer id_detalle_pago);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int insert(DetallePago record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int insertSelective(DetallePago record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    List<DetallePago> selectByExample(DetallePagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    DetallePago selectByPrimaryKey(Integer id_detalle_pago);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int updateByExampleSelective(@Param("record") DetallePago record, @Param("example") DetallePagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int updateByExample(@Param("record") DetallePago record, @Param("example") DetallePagoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int updateByPrimaryKeySelective(DetallePago record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detalle_pago
     *
     * @mbggenerated Thu Mar 10 16:44:01 COT 2016
     */
    int updateByPrimaryKey(DetallePago record);
}