package com.colsevi.dao.pago.map;

import com.colsevi.dao.pago.model.PagoProveedor;
import com.colsevi.dao.pago.model.PagoProveedorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PagoProveedorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int countByExample(PagoProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int deleteByExample(PagoProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int deleteByPrimaryKey(Integer id_pago_proveedor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int insert(PagoProveedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int insertSelective(PagoProveedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    List<PagoProveedor> selectByExample(PagoProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    PagoProveedor selectByPrimaryKey(Integer id_pago_proveedor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int updateByExampleSelective(@Param("record") PagoProveedor record, @Param("example") PagoProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int updateByExample(@Param("record") PagoProveedor record, @Param("example") PagoProveedorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int updateByPrimaryKeySelective(PagoProveedor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pago_proveedor
     *
     * @mbggenerated Tue Apr 12 16:29:49 COT 2016
     */
    int updateByPrimaryKey(PagoProveedor record);
    
    List<Map<String, Object>> deudaCom(Map<String, Object> mapa);
}