package com.colsevi.dao.pago.map;

import com.colsevi.dao.pago.model.PagoProveedor;
import com.colsevi.dao.pago.model.PagoProveedorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PagoProveedorMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	long countByExample(PagoProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int deleteByExample(PagoProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_pago_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int insert(PagoProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int insertSelective(PagoProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	List<PagoProveedor> selectByExample(PagoProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	PagoProveedor selectByPrimaryKey(Integer id_pago_proveedor);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int updateByExampleSelective(@Param("record") PagoProveedor record, @Param("example") PagoProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int updateByExample(@Param("record") PagoProveedor record, @Param("example") PagoProveedorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int updateByPrimaryKeySelective(PagoProveedor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_proveedor
	 * @mbg.generated  Fri Apr 28 17:35:03 COT 2017
	 */
	int updateByPrimaryKey(PagoProveedor record);

	List<Map<String, Object>> deudaCom(Map<String, Object> mapa);
}