package com.colsevi.dao.pago.map;

import com.colsevi.dao.pago.model.PagoPedido;
import com.colsevi.dao.pago.model.PagoPedidoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PagoPedidoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	long countByExample(PagoPedidoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int deleteByExample(PagoPedidoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_pago_pedido);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int insert(PagoPedido record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int insertSelective(PagoPedido record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	List<PagoPedido> selectByExample(PagoPedidoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	PagoPedido selectByPrimaryKey(Integer id_pago_pedido);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int updateByExampleSelective(@Param("record") PagoPedido record, @Param("example") PagoPedidoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int updateByExample(@Param("record") PagoPedido record, @Param("example") PagoPedidoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int updateByPrimaryKeySelective(PagoPedido record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pago_pedido
	 * @mbg.generated  Fri Apr 28 17:55:54 COT 2017
	 */
	int updateByPrimaryKey(PagoPedido record);
}