package com.colsevi.dao.ingrediente.map;

import com.colsevi.dao.ingrediente.model.ClasificarIngrediente;
import com.colsevi.dao.ingrediente.model.ClasificarIngredienteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClasificarIngredienteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int countByExample(ClasificarIngredienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int deleteByExample(ClasificarIngredienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int deleteByPrimaryKey(Integer id_clasificar_ingrediente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int insert(ClasificarIngrediente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int insertSelective(ClasificarIngrediente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    List<ClasificarIngrediente> selectByExample(ClasificarIngredienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    ClasificarIngrediente selectByPrimaryKey(Integer id_clasificar_ingrediente);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int updateByExampleSelective(@Param("record") ClasificarIngrediente record, @Param("example") ClasificarIngredienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int updateByExample(@Param("record") ClasificarIngrediente record, @Param("example") ClasificarIngredienteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int updateByPrimaryKeySelective(ClasificarIngrediente record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clasificar_ingrediente
     *
     * @mbggenerated Mon Mar 21 22:55:56 COT 2016
     */
    int updateByPrimaryKey(ClasificarIngrediente record);
}