package com.colsevi.dao.ingrediente.map;

import com.colsevi.dao.ingrediente.model.TipoPeso;
import com.colsevi.dao.ingrediente.model.TipoPesoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoPesoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int countByExample(TipoPesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int deleteByExample(TipoPesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int deleteByPrimaryKey(Integer id_tipo_peso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int insert(TipoPeso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int insertSelective(TipoPeso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    List<TipoPeso> selectByExample(TipoPesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    TipoPeso selectByPrimaryKey(Integer id_tipo_peso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int updateByExampleSelective(@Param("record") TipoPeso record, @Param("example") TipoPesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int updateByExample(@Param("record") TipoPeso record, @Param("example") TipoPesoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int updateByPrimaryKeySelective(TipoPeso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipo_peso
     *
     * @mbggenerated Thu Mar 10 16:27:51 COT 2016
     */
    int updateByPrimaryKey(TipoPeso record);
}