package com.colsevi.dao.producto.model;

public class IngredienteXProductoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingrediente_x_producto.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	private Integer id_ingrediente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingrediente_x_producto.id_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	private Integer id_producto;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingrediente_x_producto.id_ingrediente
	 * @return  the value of ingrediente_x_producto.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public Integer getId_ingrediente() {
		return id_ingrediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingrediente_x_producto.id_ingrediente
	 * @param id_ingrediente  the value for ingrediente_x_producto.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public void setId_ingrediente(Integer id_ingrediente) {
		this.id_ingrediente = id_ingrediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingrediente_x_producto.id_producto
	 * @return  the value of ingrediente_x_producto.id_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public Integer getId_producto() {
		return id_producto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingrediente_x_producto.id_producto
	 * @param id_producto  the value for ingrediente_x_producto.id_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public void setId_producto(Integer id_producto) {
		this.id_producto = id_producto;
	}
}