package com.colsevi.dao.producto.model;

public class Receta {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receta.id_receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	private Integer id_receta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receta.id_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	private Integer id_producto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receta.id_dificultad_receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	private Integer id_dificultad_receta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column receta.tiempo
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	private String tiempo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receta.id_receta
	 * @return  the value of receta.id_receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public Integer getId_receta() {
		return id_receta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receta.id_receta
	 * @param id_receta  the value for receta.id_receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public void setId_receta(Integer id_receta) {
		this.id_receta = id_receta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receta.id_producto
	 * @return  the value of receta.id_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public Integer getId_producto() {
		return id_producto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receta.id_producto
	 * @param id_producto  the value for receta.id_producto
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public void setId_producto(Integer id_producto) {
		this.id_producto = id_producto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receta.id_dificultad_receta
	 * @return  the value of receta.id_dificultad_receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public Integer getId_dificultad_receta() {
		return id_dificultad_receta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receta.id_dificultad_receta
	 * @param id_dificultad_receta  the value for receta.id_dificultad_receta
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public void setId_dificultad_receta(Integer id_dificultad_receta) {
		this.id_dificultad_receta = id_dificultad_receta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column receta.tiempo
	 * @return  the value of receta.tiempo
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public String getTiempo() {
		return tiempo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column receta.tiempo
	 * @param tiempo  the value for receta.tiempo
	 * @mbg.generated  Fri Apr 28 17:49:43 COT 2017
	 */
	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}
}