package com.colsevi.dao.usuario.model;

public class PaginaXRolKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pagina_x_rol.id_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private Integer id_rol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pagina_x_rol.id_pagina
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private Integer id_pagina;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pagina_x_rol.id_rol
	 * @return  the value of pagina_x_rol.id_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public Integer getId_rol() {
		return id_rol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pagina_x_rol.id_rol
	 * @param id_rol  the value for pagina_x_rol.id_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setId_rol(Integer id_rol) {
		this.id_rol = id_rol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pagina_x_rol.id_pagina
	 * @return  the value of pagina_x_rol.id_pagina
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public Integer getId_pagina() {
		return id_pagina;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pagina_x_rol.id_pagina
	 * @param id_pagina  the value for pagina_x_rol.id_pagina
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setId_pagina(Integer id_pagina) {
		this.id_pagina = id_pagina;
	}
}