package com.colsevi.dao.usuario.model;

import java.util.ArrayList;
import java.util.List;

public class PaginaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public PaginaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andId_paginaIsNull() {
			addCriterion("id_pagina is null");
			return (Criteria) this;
		}

		public Criteria andId_paginaIsNotNull() {
			addCriterion("id_pagina is not null");
			return (Criteria) this;
		}

		public Criteria andId_paginaEqualTo(Integer value) {
			addCriterion("id_pagina =", value, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaNotEqualTo(Integer value) {
			addCriterion("id_pagina <>", value, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaGreaterThan(Integer value) {
			addCriterion("id_pagina >", value, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_pagina >=", value, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaLessThan(Integer value) {
			addCriterion("id_pagina <", value, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaLessThanOrEqualTo(Integer value) {
			addCriterion("id_pagina <=", value, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaIn(List<Integer> values) {
			addCriterion("id_pagina in", values, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaNotIn(List<Integer> values) {
			addCriterion("id_pagina not in", values, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaBetween(Integer value1, Integer value2) {
			addCriterion("id_pagina between", value1, value2, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andId_paginaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_pagina not between", value1, value2, "id_pagina");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaIsNull() {
			addCriterion("padrePagina is null");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaIsNotNull() {
			addCriterion("padrePagina is not null");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaEqualTo(String value) {
			addCriterion("padrePagina =", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaNotEqualTo(String value) {
			addCriterion("padrePagina <>", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaGreaterThan(String value) {
			addCriterion("padrePagina >", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaGreaterThanOrEqualTo(String value) {
			addCriterion("padrePagina >=", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaLessThan(String value) {
			addCriterion("padrePagina <", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaLessThanOrEqualTo(String value) {
			addCriterion("padrePagina <=", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaLike(String value) {
			addCriterion("padrePagina like", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaNotLike(String value) {
			addCriterion("padrePagina not like", value, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaIn(List<String> values) {
			addCriterion("padrePagina in", values, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaNotIn(List<String> values) {
			addCriterion("padrePagina not in", values, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaBetween(String value1, String value2) {
			addCriterion("padrePagina between", value1, value2, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andPadrePaginaNotBetween(String value1, String value2) {
			addCriterion("padrePagina not between", value1, value2, "padrePagina");
			return (Criteria) this;
		}

		public Criteria andMenuIsNull() {
			addCriterion("menu is null");
			return (Criteria) this;
		}

		public Criteria andMenuIsNotNull() {
			addCriterion("menu is not null");
			return (Criteria) this;
		}

		public Criteria andMenuEqualTo(Boolean value) {
			addCriterion("menu =", value, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuNotEqualTo(Boolean value) {
			addCriterion("menu <>", value, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuGreaterThan(Boolean value) {
			addCriterion("menu >", value, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuGreaterThanOrEqualTo(Boolean value) {
			addCriterion("menu >=", value, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuLessThan(Boolean value) {
			addCriterion("menu <", value, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuLessThanOrEqualTo(Boolean value) {
			addCriterion("menu <=", value, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuIn(List<Boolean> values) {
			addCriterion("menu in", values, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuNotIn(List<Boolean> values) {
			addCriterion("menu not in", values, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuBetween(Boolean value1, Boolean value2) {
			addCriterion("menu between", value1, value2, "menu");
			return (Criteria) this;
		}

		public Criteria andMenuNotBetween(Boolean value1, Boolean value2) {
			addCriterion("menu not between", value1, value2, "menu");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pagina
	 * @mbg.generated  Fri Apr 28 17:29:08 COT 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pagina
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 03 21:54:29 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}