package com.colsevi.dao.usuario.model;

public class Persona {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.id_persona
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	private Integer id_persona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.tipo_doc
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	private Integer tipo_doc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.documento
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	private String documento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.genero
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	private String genero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.nombre
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column persona.apellido
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	private String apellido;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.id_persona
	 * @return  the value of persona.id_persona
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public Integer getId_persona() {
		return id_persona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.id_persona
	 * @param id_persona  the value for persona.id_persona
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public void setId_persona(Integer id_persona) {
		this.id_persona = id_persona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.tipo_doc
	 * @return  the value of persona.tipo_doc
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public Integer getTipo_doc() {
		return tipo_doc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.tipo_doc
	 * @param tipo_doc  the value for persona.tipo_doc
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public void setTipo_doc(Integer tipo_doc) {
		this.tipo_doc = tipo_doc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.documento
	 * @return  the value of persona.documento
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public String getDocumento() {
		return documento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.documento
	 * @param documento  the value for persona.documento
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public void setDocumento(String documento) {
		this.documento = documento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.genero
	 * @return  the value of persona.genero
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public String getGenero() {
		return genero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.genero
	 * @param genero  the value for persona.genero
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public void setGenero(String genero) {
		this.genero = genero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.nombre
	 * @return  the value of persona.nombre
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.nombre
	 * @param nombre  the value for persona.nombre
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column persona.apellido
	 * @return  the value of persona.apellido
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public String getApellido() {
		return apellido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column persona.apellido
	 * @param apellido  the value for persona.apellido
	 * @mbg.generated  Fri Apr 28 17:26:23 COT 2017
	 */
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}
}