package com.colsevi.dao.usuario.model;

public class Rol {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol.id_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private Integer id_rol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol.nombre_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private String nombre_rol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol.codigo_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private String codigo_rol;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol.id_rol
	 * @return  the value of rol.id_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public Integer getId_rol() {
		return id_rol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol.id_rol
	 * @param id_rol  the value for rol.id_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setId_rol(Integer id_rol) {
		this.id_rol = id_rol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol.nombre_rol
	 * @return  the value of rol.nombre_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public String getNombre_rol() {
		return nombre_rol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol.nombre_rol
	 * @param nombre_rol  the value for rol.nombre_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setNombre_rol(String nombre_rol) {
		this.nombre_rol = nombre_rol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol.codigo_rol
	 * @return  the value of rol.codigo_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public String getCodigo_rol() {
		return codigo_rol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol.codigo_rol
	 * @param codigo_rol  the value for rol.codigo_rol
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setCodigo_rol(String codigo_rol) {
		this.codigo_rol = codigo_rol;
	}
}