package com.colsevi.dao.usuario.model;

import java.util.ArrayList;
import java.util.List;

public class RolExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public RolExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andId_rolIsNull() {
            addCriterion("id_rol is null");
            return (Criteria) this;
        }

        public Criteria andId_rolIsNotNull() {
            addCriterion("id_rol is not null");
            return (Criteria) this;
        }

        public Criteria andId_rolEqualTo(Integer value) {
            addCriterion("id_rol =", value, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolNotEqualTo(Integer value) {
            addCriterion("id_rol <>", value, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolGreaterThan(Integer value) {
            addCriterion("id_rol >", value, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_rol >=", value, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolLessThan(Integer value) {
            addCriterion("id_rol <", value, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolLessThanOrEqualTo(Integer value) {
            addCriterion("id_rol <=", value, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolIn(List<Integer> values) {
            addCriterion("id_rol in", values, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolNotIn(List<Integer> values) {
            addCriterion("id_rol not in", values, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolBetween(Integer value1, Integer value2) {
            addCriterion("id_rol between", value1, value2, "id_rol");
            return (Criteria) this;
        }

        public Criteria andId_rolNotBetween(Integer value1, Integer value2) {
            addCriterion("id_rol not between", value1, value2, "id_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolIsNull() {
            addCriterion("nombre_rol is null");
            return (Criteria) this;
        }

        public Criteria andNombre_rolIsNotNull() {
            addCriterion("nombre_rol is not null");
            return (Criteria) this;
        }

        public Criteria andNombre_rolEqualTo(Integer value) {
            addCriterion("nombre_rol =", value, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolNotEqualTo(Integer value) {
            addCriterion("nombre_rol <>", value, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolGreaterThan(Integer value) {
            addCriterion("nombre_rol >", value, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolGreaterThanOrEqualTo(Integer value) {
            addCriterion("nombre_rol >=", value, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolLessThan(Integer value) {
            addCriterion("nombre_rol <", value, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolLessThanOrEqualTo(Integer value) {
            addCriterion("nombre_rol <=", value, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolIn(List<Integer> values) {
            addCriterion("nombre_rol in", values, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolNotIn(List<Integer> values) {
            addCriterion("nombre_rol not in", values, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolBetween(Integer value1, Integer value2) {
            addCriterion("nombre_rol between", value1, value2, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andNombre_rolNotBetween(Integer value1, Integer value2) {
            addCriterion("nombre_rol not between", value1, value2, "nombre_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolIsNull() {
            addCriterion("codigo_rol is null");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolIsNotNull() {
            addCriterion("codigo_rol is not null");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolEqualTo(String value) {
            addCriterion("codigo_rol =", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolNotEqualTo(String value) {
            addCriterion("codigo_rol <>", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolGreaterThan(String value) {
            addCriterion("codigo_rol >", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_rol >=", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolLessThan(String value) {
            addCriterion("codigo_rol <", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolLessThanOrEqualTo(String value) {
            addCriterion("codigo_rol <=", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolLike(String value) {
            addCriterion("codigo_rol like", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolNotLike(String value) {
            addCriterion("codigo_rol not like", value, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolIn(List<String> values) {
            addCriterion("codigo_rol in", values, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolNotIn(List<String> values) {
            addCriterion("codigo_rol not in", values, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolBetween(String value1, String value2) {
            addCriterion("codigo_rol between", value1, value2, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andCodigo_rolNotBetween(String value1, String value2) {
            addCriterion("codigo_rol not between", value1, value2, "codigo_rol");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoIsNull() {
            addCriterion("pagina_defecto is null");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoIsNotNull() {
            addCriterion("pagina_defecto is not null");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoEqualTo(Integer value) {
            addCriterion("pagina_defecto =", value, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoNotEqualTo(Integer value) {
            addCriterion("pagina_defecto <>", value, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoGreaterThan(Integer value) {
            addCriterion("pagina_defecto >", value, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoGreaterThanOrEqualTo(Integer value) {
            addCriterion("pagina_defecto >=", value, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoLessThan(Integer value) {
            addCriterion("pagina_defecto <", value, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoLessThanOrEqualTo(Integer value) {
            addCriterion("pagina_defecto <=", value, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoIn(List<Integer> values) {
            addCriterion("pagina_defecto in", values, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoNotIn(List<Integer> values) {
            addCriterion("pagina_defecto not in", values, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoBetween(Integer value1, Integer value2) {
            addCriterion("pagina_defecto between", value1, value2, "pagina_defecto");
            return (Criteria) this;
        }

        public Criteria andPagina_defectoNotBetween(Integer value1, Integer value2) {
            addCriterion("pagina_defecto not between", value1, value2, "pagina_defecto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rol
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 03 21:54:43 COT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rol
     *
     * @mbggenerated Thu Dec 03 21:54:43 COT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}