package com.colsevi.dao.usuario.model;

public class TipoDocumento {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_documento.id_tipo_documento
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private Integer id_tipo_documento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_documento.nombre
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tipo_documento.descripcion
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_documento.id_tipo_documento
	 * @return  the value of tipo_documento.id_tipo_documento
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public Integer getId_tipo_documento() {
		return id_tipo_documento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_documento.id_tipo_documento
	 * @param id_tipo_documento  the value for tipo_documento.id_tipo_documento
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setId_tipo_documento(Integer id_tipo_documento) {
		this.id_tipo_documento = id_tipo_documento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_documento.nombre
	 * @return  the value of tipo_documento.nombre
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_documento.nombre
	 * @param nombre  the value for tipo_documento.nombre
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tipo_documento.descripcion
	 * @return  the value of tipo_documento.descripcion
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tipo_documento.descripcion
	 * @param descripcion  the value for tipo_documento.descripcion
	 * @mbggenerated  Tue Apr 12 16:35:11 COT 2016
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}