package com.colsevi.dao.usuario.model;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.usuario
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    private String usuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.clave
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    private String clave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.codigo
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    private Integer codigo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.estado
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    private String estado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.usuario
     *
     * @return the value of usuario.usuario
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.usuario
     *
     * @param usuario the value for usuario.usuario
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.clave
     *
     * @return the value of usuario.clave
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public String getClave() {
        return clave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.clave
     *
     * @param clave the value for usuario.clave
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public void setClave(String clave) {
        this.clave = clave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.codigo
     *
     * @return the value of usuario.codigo
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.codigo
     *
     * @param codigo the value for usuario.codigo
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.estado
     *
     * @return the value of usuario.estado
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.estado
     *
     * @param estado the value for usuario.estado
     *
     * @mbggenerated Sat Nov 21 14:53:37 COT 2015
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }
}