package com.colsevi.dao.proveedor.model;

import java.math.BigDecimal;
import java.util.Date;

public class CompraProveedor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.id_compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer id_compra_proveedor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.id_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer id_proveedor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.id_establecimiento
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer id_establecimiento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.valor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private BigDecimal valor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.fecha_compra
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Date fecha_compra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.iva
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer iva;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.pagado
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Boolean pagado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.motivo
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private String motivo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.pendiente
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private BigDecimal pendiente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_proveedor.observacion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private String observacion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.id_compra_proveedor
	 * @return  the value of compra_proveedor.id_compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getId_compra_proveedor() {
		return id_compra_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.id_compra_proveedor
	 * @param id_compra_proveedor  the value for compra_proveedor.id_compra_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setId_compra_proveedor(Integer id_compra_proveedor) {
		this.id_compra_proveedor = id_compra_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.id_proveedor
	 * @return  the value of compra_proveedor.id_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getId_proveedor() {
		return id_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.id_proveedor
	 * @param id_proveedor  the value for compra_proveedor.id_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setId_proveedor(Integer id_proveedor) {
		this.id_proveedor = id_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.id_establecimiento
	 * @return  the value of compra_proveedor.id_establecimiento
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getId_establecimiento() {
		return id_establecimiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.id_establecimiento
	 * @param id_establecimiento  the value for compra_proveedor.id_establecimiento
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setId_establecimiento(Integer id_establecimiento) {
		this.id_establecimiento = id_establecimiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.valor
	 * @return  the value of compra_proveedor.valor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public BigDecimal getValor() {
		return valor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.valor
	 * @param valor  the value for compra_proveedor.valor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.fecha_compra
	 * @return  the value of compra_proveedor.fecha_compra
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Date getFecha_compra() {
		return fecha_compra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.fecha_compra
	 * @param fecha_compra  the value for compra_proveedor.fecha_compra
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setFecha_compra(Date fecha_compra) {
		this.fecha_compra = fecha_compra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.iva
	 * @return  the value of compra_proveedor.iva
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getIva() {
		return iva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.iva
	 * @param iva  the value for compra_proveedor.iva
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setIva(Integer iva) {
		this.iva = iva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.pagado
	 * @return  the value of compra_proveedor.pagado
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Boolean getPagado() {
		return pagado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.pagado
	 * @param pagado  the value for compra_proveedor.pagado
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setPagado(Boolean pagado) {
		this.pagado = pagado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.motivo
	 * @return  the value of compra_proveedor.motivo
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public String getMotivo() {
		return motivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.motivo
	 * @param motivo  the value for compra_proveedor.motivo
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.pendiente
	 * @return  the value of compra_proveedor.pendiente
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public BigDecimal getPendiente() {
		return pendiente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.pendiente
	 * @param pendiente  the value for compra_proveedor.pendiente
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setPendiente(BigDecimal pendiente) {
		this.pendiente = pendiente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_proveedor.observacion
	 * @return  the value of compra_proveedor.observacion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public String getObservacion() {
		return observacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_proveedor.observacion
	 * @param observacion  the value for compra_proveedor.observacion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
}