package com.colsevi.dao.proveedor.model;

public class CompraXIngredienteKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.id_compra
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	private Integer id_compra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	private Integer id_ingrediente;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.id_compra
	 * @return  the value of compra_x_ingrediente.id_compra
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public Integer getId_compra() {
		return id_compra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.id_compra
	 * @param id_compra  the value for compra_x_ingrediente.id_compra
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public void setId_compra(Integer id_compra) {
		this.id_compra = id_compra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.id_ingrediente
	 * @return  the value of compra_x_ingrediente.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public Integer getId_ingrediente() {
		return id_ingrediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.id_ingrediente
	 * @param id_ingrediente  the value for compra_x_ingrediente.id_ingrediente
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public void setId_ingrediente(Integer id_ingrediente) {
		this.id_ingrediente = id_ingrediente;
	}
}