package com.colsevi.dao.proveedor.model;

import java.util.Date;
import java.math.BigDecimal;

public class CompraXIngrediente extends CompraXIngredienteKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.id_unidad_peso
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	private Integer id_unidad_peso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.cantidad
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	private Double cantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.vunitario
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	private BigDecimal vunitario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.fecha_vencimiento
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	private Date fecha_vencimiento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.lote
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	private Integer lote;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.id_unidad_peso
	 * @return  the value of compra_x_ingrediente.id_unidad_peso
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public Integer getId_unidad_peso() {
		return id_unidad_peso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.id_unidad_peso
	 * @param id_unidad_peso  the value for compra_x_ingrediente.id_unidad_peso
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public void setId_unidad_peso(Integer id_unidad_peso) {
		this.id_unidad_peso = id_unidad_peso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.cantidad
	 * @return  the value of compra_x_ingrediente.cantidad
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public Double getCantidad() {
		return cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.cantidad
	 * @param cantidad  the value for compra_x_ingrediente.cantidad
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.vunitario
	 * @return  the value of compra_x_ingrediente.vunitario
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public BigDecimal getVunitario() {
		return vunitario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.vunitario
	 * @param vunitario  the value for compra_x_ingrediente.vunitario
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public void setVunitario(BigDecimal vunitario) {
		this.vunitario = vunitario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.fecha_vencimiento
	 * @return  the value of compra_x_ingrediente.fecha_vencimiento
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public Date getFecha_vencimiento() {
		return fecha_vencimiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.fecha_vencimiento
	 * @param fecha_vencimiento  the value for compra_x_ingrediente.fecha_vencimiento
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public void setFecha_vencimiento(Date fecha_vencimiento) {
		this.fecha_vencimiento = fecha_vencimiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.lote
	 * @return  the value of compra_x_ingrediente.lote
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public Integer getLote() {
		return lote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.lote
	 * @param lote  the value for compra_x_ingrediente.lote
	 * @mbg.generated  Fri Apr 28 17:43:32 COT 2017
	 */
	public void setLote(Integer lote) {
		this.lote = lote;
	}
}