package com.colsevi.dao.proveedor.model;

public class CompraXIngredienteKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.lote
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	private Integer lote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.id_compra
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	private Integer id_compra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compra_x_ingrediente.id_ingrediente
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	private Integer id_ingrediente;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.lote
	 * @return  the value of compra_x_ingrediente.lote
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	public Integer getLote() {
		return lote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.lote
	 * @param lote  the value for compra_x_ingrediente.lote
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	public void setLote(Integer lote) {
		this.lote = lote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.id_compra
	 * @return  the value of compra_x_ingrediente.id_compra
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	public Integer getId_compra() {
		return id_compra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.id_compra
	 * @param id_compra  the value for compra_x_ingrediente.id_compra
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	public void setId_compra(Integer id_compra) {
		this.id_compra = id_compra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compra_x_ingrediente.id_ingrediente
	 * @return  the value of compra_x_ingrediente.id_ingrediente
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	public Integer getId_ingrediente() {
		return id_ingrediente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compra_x_ingrediente.id_ingrediente
	 * @param id_ingrediente  the value for compra_x_ingrediente.id_ingrediente
	 * @mbggenerated  Tue Apr 12 16:29:08 COT 2016
	 */
	public void setId_ingrediente(Integer id_ingrediente) {
		this.id_ingrediente = id_ingrediente;
	}
}