package com.colsevi.dao.proveedor.model;

public class Proveedor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.id_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer id_proveedor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.id_direccion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer id_direccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.id_tipo_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer id_tipo_proveedor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.id_telefono
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private Integer id_telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.nombre
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.descripcion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	private String descripcion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.id_proveedor
	 * @return  the value of proveedor.id_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getId_proveedor() {
		return id_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.id_proveedor
	 * @param id_proveedor  the value for proveedor.id_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setId_proveedor(Integer id_proveedor) {
		this.id_proveedor = id_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.id_direccion
	 * @return  the value of proveedor.id_direccion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getId_direccion() {
		return id_direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.id_direccion
	 * @param id_direccion  the value for proveedor.id_direccion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setId_direccion(Integer id_direccion) {
		this.id_direccion = id_direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.id_tipo_proveedor
	 * @return  the value of proveedor.id_tipo_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getId_tipo_proveedor() {
		return id_tipo_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.id_tipo_proveedor
	 * @param id_tipo_proveedor  the value for proveedor.id_tipo_proveedor
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setId_tipo_proveedor(Integer id_tipo_proveedor) {
		this.id_tipo_proveedor = id_tipo_proveedor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.id_telefono
	 * @return  the value of proveedor.id_telefono
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public Integer getId_telefono() {
		return id_telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.id_telefono
	 * @param id_telefono  the value for proveedor.id_telefono
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setId_telefono(Integer id_telefono) {
		this.id_telefono = id_telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.nombre
	 * @return  the value of proveedor.nombre
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.nombre
	 * @param nombre  the value for proveedor.nombre
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.descripcion
	 * @return  the value of proveedor.descripcion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.descripcion
	 * @param descripcion  the value for proveedor.descripcion
	 * @mbg.generated  Fri Apr 28 17:33:30 COT 2017
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}