package com.colsevi.dao.pedido.map;

import com.colsevi.dao.pedido.model.CategoriaCobro;
import com.colsevi.dao.pedido.model.CategoriaCobroExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoriaCobroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int countByExample(CategoriaCobroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int deleteByExample(CategoriaCobroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int deleteByPrimaryKey(Integer id_categoria_cobro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int insert(CategoriaCobro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int insertSelective(CategoriaCobro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    List<CategoriaCobro> selectByExample(CategoriaCobroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    CategoriaCobro selectByPrimaryKey(Integer id_categoria_cobro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int updateByExampleSelective(@Param("record") CategoriaCobro record, @Param("example") CategoriaCobroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int updateByExample(@Param("record") CategoriaCobro record, @Param("example") CategoriaCobroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int updateByPrimaryKeySelective(CategoriaCobro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    int updateByPrimaryKey(CategoriaCobro record);
}