package com.colsevi.dao.pedido.map;

import com.colsevi.dao.pedido.model.Cobro;
import com.colsevi.dao.pedido.model.CobroExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CobroMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	long countByExample(CobroExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int deleteByExample(CobroExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_cobro);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int insert(Cobro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int insertSelective(Cobro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	List<Cobro> selectByExample(CobroExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	Cobro selectByPrimaryKey(Integer id_cobro);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Cobro record, @Param("example") CobroExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int updateByExample(@Param("record") Cobro record, @Param("example") CobroExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int updateByPrimaryKeySelective(Cobro record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cobro
	 * @mbg.generated  Fri Apr 28 17:58:25 COT 2017
	 */
	int updateByPrimaryKey(Cobro record);
}