package com.colsevi.dao.pedido.model;

public class CategoriaCobro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categoria_cobro.id_categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    private Integer id_categoria_cobro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categoria_cobro.nombre
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categoria_cobro.id_categoria_cobro
     *
     * @return the value of categoria_cobro.id_categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public Integer getId_categoria_cobro() {
        return id_categoria_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categoria_cobro.id_categoria_cobro
     *
     * @param id_categoria_cobro the value for categoria_cobro.id_categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public void setId_categoria_cobro(Integer id_categoria_cobro) {
        this.id_categoria_cobro = id_categoria_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categoria_cobro.nombre
     *
     * @return the value of categoria_cobro.nombre
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categoria_cobro.nombre
     *
     * @param nombre the value for categoria_cobro.nombre
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}