package com.colsevi.dao.pedido.model;

import java.util.Date;

public class Cobro {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cobro.id_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    private Integer id_cobro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cobro.id_deuda
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    private Integer id_deuda;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cobro.id_categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    private Integer id_categoria_cobro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cobro.fecha_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    private Date fecha_cobro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cobro.comentario
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    private String comentario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cobro.id_cobro
     *
     * @return the value of cobro.id_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public Integer getId_cobro() {
        return id_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cobro.id_cobro
     *
     * @param id_cobro the value for cobro.id_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public void setId_cobro(Integer id_cobro) {
        this.id_cobro = id_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cobro.id_deuda
     *
     * @return the value of cobro.id_deuda
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public Integer getId_deuda() {
        return id_deuda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cobro.id_deuda
     *
     * @param id_deuda the value for cobro.id_deuda
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public void setId_deuda(Integer id_deuda) {
        this.id_deuda = id_deuda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cobro.id_categoria_cobro
     *
     * @return the value of cobro.id_categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public Integer getId_categoria_cobro() {
        return id_categoria_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cobro.id_categoria_cobro
     *
     * @param id_categoria_cobro the value for cobro.id_categoria_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public void setId_categoria_cobro(Integer id_categoria_cobro) {
        this.id_categoria_cobro = id_categoria_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cobro.fecha_cobro
     *
     * @return the value of cobro.fecha_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public Date getFecha_cobro() {
        return fecha_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cobro.fecha_cobro
     *
     * @param fecha_cobro the value for cobro.fecha_cobro
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public void setFecha_cobro(Date fecha_cobro) {
        this.fecha_cobro = fecha_cobro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cobro.comentario
     *
     * @return the value of cobro.comentario
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cobro.comentario
     *
     * @param comentario the value for cobro.comentario
     *
     * @mbggenerated Tue Apr 12 16:28:01 COT 2016
     */
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
}