package com.colsevi.dao.pedido.model;

import java.math.BigDecimal;

public class DetallePedido {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detalle_pedido.id_detalle_pedido
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	private Integer id_detalle_pedido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detalle_pedido.id_pedido
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	private Integer id_pedido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detalle_pedido.id_producto
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	private Integer id_producto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detalle_pedido.cantidad
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	private Integer cantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column detalle_pedido.sub_total
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	private BigDecimal sub_total;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detalle_pedido.id_detalle_pedido
	 * @return  the value of detalle_pedido.id_detalle_pedido
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public Integer getId_detalle_pedido() {
		return id_detalle_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detalle_pedido.id_detalle_pedido
	 * @param id_detalle_pedido  the value for detalle_pedido.id_detalle_pedido
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public void setId_detalle_pedido(Integer id_detalle_pedido) {
		this.id_detalle_pedido = id_detalle_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detalle_pedido.id_pedido
	 * @return  the value of detalle_pedido.id_pedido
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public Integer getId_pedido() {
		return id_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detalle_pedido.id_pedido
	 * @param id_pedido  the value for detalle_pedido.id_pedido
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public void setId_pedido(Integer id_pedido) {
		this.id_pedido = id_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detalle_pedido.id_producto
	 * @return  the value of detalle_pedido.id_producto
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public Integer getId_producto() {
		return id_producto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detalle_pedido.id_producto
	 * @param id_producto  the value for detalle_pedido.id_producto
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public void setId_producto(Integer id_producto) {
		this.id_producto = id_producto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detalle_pedido.cantidad
	 * @return  the value of detalle_pedido.cantidad
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detalle_pedido.cantidad
	 * @param cantidad  the value for detalle_pedido.cantidad
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column detalle_pedido.sub_total
	 * @return  the value of detalle_pedido.sub_total
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public BigDecimal getSub_total() {
		return sub_total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column detalle_pedido.sub_total
	 * @param sub_total  the value for detalle_pedido.sub_total
	 * @mbg.generated  Fri Apr 28 17:54:59 COT 2017
	 */
	public void setSub_total(BigDecimal sub_total) {
		this.sub_total = sub_total;
	}
}