package com.colsevi.dao.pedido.model;

import java.math.BigDecimal;
import java.util.Date;

public class Pedido {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.id_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private Integer id_pedido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.id_persona
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private Integer id_persona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.id_estado_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private Integer id_estado_pedido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.total
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private BigDecimal total;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.fecha_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private Date fecha_pedido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.pagado
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private Boolean pagado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.id_establecimiento
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private Integer id_establecimiento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.comentario
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private String comentario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pedido.motivo
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	private Integer motivo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.id_pedido
	 * @return  the value of pedido.id_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public Integer getId_pedido() {
		return id_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.id_pedido
	 * @param id_pedido  the value for pedido.id_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setId_pedido(Integer id_pedido) {
		this.id_pedido = id_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.id_persona
	 * @return  the value of pedido.id_persona
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public Integer getId_persona() {
		return id_persona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.id_persona
	 * @param id_persona  the value for pedido.id_persona
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setId_persona(Integer id_persona) {
		this.id_persona = id_persona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.id_estado_pedido
	 * @return  the value of pedido.id_estado_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public Integer getId_estado_pedido() {
		return id_estado_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.id_estado_pedido
	 * @param id_estado_pedido  the value for pedido.id_estado_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setId_estado_pedido(Integer id_estado_pedido) {
		this.id_estado_pedido = id_estado_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.total
	 * @return  the value of pedido.total
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public BigDecimal getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.total
	 * @param total  the value for pedido.total
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.fecha_pedido
	 * @return  the value of pedido.fecha_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public Date getFecha_pedido() {
		return fecha_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.fecha_pedido
	 * @param fecha_pedido  the value for pedido.fecha_pedido
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setFecha_pedido(Date fecha_pedido) {
		this.fecha_pedido = fecha_pedido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.pagado
	 * @return  the value of pedido.pagado
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public Boolean getPagado() {
		return pagado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.pagado
	 * @param pagado  the value for pedido.pagado
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setPagado(Boolean pagado) {
		this.pagado = pagado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.id_establecimiento
	 * @return  the value of pedido.id_establecimiento
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public Integer getId_establecimiento() {
		return id_establecimiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.id_establecimiento
	 * @param id_establecimiento  the value for pedido.id_establecimiento
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setId_establecimiento(Integer id_establecimiento) {
		this.id_establecimiento = id_establecimiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.comentario
	 * @return  the value of pedido.comentario
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public String getComentario() {
		return comentario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.comentario
	 * @param comentario  the value for pedido.comentario
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pedido.motivo
	 * @return  the value of pedido.motivo
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public Integer getMotivo() {
		return motivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pedido.motivo
	 * @param motivo  the value for pedido.motivo
	 * @mbggenerated  Tue May 24 12:18:48 COT 2016
	 */
	public void setMotivo(Integer motivo) {
		this.motivo = motivo;
	}
}