package com.colsevi.dao.general.map;

import com.colsevi.dao.general.model.Correo;
import com.colsevi.dao.general.model.CorreoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CorreoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int countByExample(CorreoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int deleteByExample(CorreoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int deleteByPrimaryKey(Integer id_correo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int insert(Correo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int insertSelective(Correo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	List<Correo> selectByExample(CorreoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	Correo selectByPrimaryKey(Integer id_correo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int updateByExampleSelective(@Param("record") Correo record,
			@Param("example") CorreoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int updateByExample(@Param("record") Correo record,
			@Param("example") CorreoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int updateByPrimaryKeySelective(Correo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table correo
	 * @mbggenerated  Tue Apr 12 16:26:48 COT 2016
	 */
	int updateByPrimaryKey(Correo record);
}