package com.colsevi.dao.general.map;

import com.colsevi.dao.general.model.Direccion;
import com.colsevi.dao.general.model.DireccionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DireccionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	long countByExample(DireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int deleteByExample(DireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_direccion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int insert(Direccion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int insertSelective(Direccion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	List<Direccion> selectByExample(DireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	Direccion selectByPrimaryKey(Integer id_direccion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Direccion record, @Param("example") DireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByExample(@Param("record") Direccion record, @Param("example") DireccionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByPrimaryKeySelective(Direccion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table direccion
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByPrimaryKey(Direccion record);
}