package com.colsevi.dao.general.map;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.colsevi.dao.general.model.Establecimiento;
import com.colsevi.dao.general.model.EstablecimientoExample;

public interface EstablecimientoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int countByExample(EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int deleteByExample(EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int deleteByPrimaryKey(Integer id_establecimiento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int insert(Establecimiento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int insertSelective(Establecimiento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	List<Establecimiento> selectByExample(EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	Establecimiento selectByPrimaryKey(Integer id_establecimiento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int updateByExampleSelective(@Param("record") Establecimiento record,
			@Param("example") EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int updateByExample(@Param("record") Establecimiento record, @Param("example") EstablecimientoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int updateByPrimaryKeySelective(Establecimiento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table establecimiento
	 * @mbggenerated  Thu Mar 31 23:20:28 COT 2016
	 */
	int updateByPrimaryKey(Establecimiento record);
	
	List<Map<String, Object>> SelectDataView(Map<String, Object> map);
	
	int CountDataView (Map<String, Object> map);
}