package com.colsevi.dao.general.map;

import com.colsevi.dao.general.model.Motivo;
import com.colsevi.dao.general.model.MotivoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MotivoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	long countByExample(MotivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int deleteByExample(MotivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_motivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int insert(Motivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int insertSelective(Motivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	List<Motivo> selectByExample(MotivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	Motivo selectByPrimaryKey(Integer id_motivo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int updateByExampleSelective(@Param("record") Motivo record, @Param("example") MotivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int updateByExample(@Param("record") Motivo record, @Param("example") MotivoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int updateByPrimaryKeySelective(Motivo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table motivo
	 * @mbg.generated  Fri Apr 28 17:44:44 COT 2017
	 */
	int updateByPrimaryKey(Motivo record);
}