package com.colsevi.dao.general.map;

import com.colsevi.dao.general.model.TipoTelefono;
import com.colsevi.dao.general.model.TipoTelefonoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipoTelefonoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	long countByExample(TipoTelefonoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int deleteByExample(TipoTelefonoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int deleteByPrimaryKey(Integer id_tipo_telefono);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int insert(TipoTelefono record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int insertSelective(TipoTelefono record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	List<TipoTelefono> selectByExample(TipoTelefonoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	TipoTelefono selectByPrimaryKey(Integer id_tipo_telefono);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByExampleSelective(@Param("record") TipoTelefono record, @Param("example") TipoTelefonoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByExample(@Param("record") TipoTelefono record, @Param("example") TipoTelefonoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByPrimaryKeySelective(TipoTelefono record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tipo_telefono
	 * @mbg.generated  Fri Apr 28 17:31:44 COT 2017
	 */
	int updateByPrimaryKey(TipoTelefono record);
}