package com.colsevi.dao.inventario.map;

import com.colsevi.dao.inventario.model.CategoriaModulo;
import com.colsevi.dao.inventario.model.CategoriaModuloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoriaModuloMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int countByExample(CategoriaModuloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int deleteByExample(CategoriaModuloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int deleteByPrimaryKey(Integer id_categoria_modulo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int insert(CategoriaModulo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int insertSelective(CategoriaModulo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    List<CategoriaModulo> selectByExample(CategoriaModuloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    CategoriaModulo selectByPrimaryKey(Integer id_categoria_modulo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int updateByExampleSelective(@Param("record") CategoriaModulo record, @Param("example") CategoriaModuloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int updateByExample(@Param("record") CategoriaModulo record, @Param("example") CategoriaModuloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int updateByPrimaryKeySelective(CategoriaModulo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table categoria_modulo
     *
     * @mbggenerated Thu Mar 10 16:42:13 COT 2016
     */
    int updateByPrimaryKey(CategoriaModulo record);
}