package com.colsevi.dao.inventario.map;

import com.colsevi.dao.inventario.model.InventarioXMateria;
import com.colsevi.dao.inventario.model.InventarioXMateriaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InventarioXMateriaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inventario_x_materia
	 * @mbggenerated  Thu Apr 21 17:19:48 COT 2016
	 */
	int countByExample(InventarioXMateriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inventario_x_materia
	 * @mbggenerated  Thu Apr 21 17:19:48 COT 2016
	 */
	int deleteByExample(InventarioXMateriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inventario_x_materia
	 * @mbggenerated  Thu Apr 21 17:19:48 COT 2016
	 */
	int insert(InventarioXMateria record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inventario_x_materia
	 * @mbggenerated  Thu Apr 21 17:19:48 COT 2016
	 */
	int insertSelective(InventarioXMateria record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inventario_x_materia
	 * @mbggenerated  Thu Apr 21 17:19:48 COT 2016
	 */
	List<InventarioXMateria> selectByExample(InventarioXMateriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inventario_x_materia
	 * @mbggenerated  Thu Apr 21 17:19:48 COT 2016
	 */
	int updateByExampleSelective(@Param("record") InventarioXMateria record,
			@Param("example") InventarioXMateriaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table inventario_x_materia
	 * @mbggenerated  Thu Apr 21 17:19:48 COT 2016
	 */
	int updateByExample(@Param("record") InventarioXMateria record,
			@Param("example") InventarioXMateriaExample example);
}