package com.colsevi.dao.inventario.map;

import com.colsevi.dao.inventario.model.MateriaPrima;
import com.colsevi.dao.inventario.model.MateriaPrimaExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MateriaPrimaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int countByExample(MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int deleteByExample(MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int deleteByPrimaryKey(Integer lote);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int insert(MateriaPrima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int insertSelective(MateriaPrima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	List<MateriaPrima> selectByExample(MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	MateriaPrima selectByPrimaryKey(Integer lote);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int updateByExampleSelective(@Param("record") MateriaPrima record, @Param("example") MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int updateByExample(@Param("record") MateriaPrima record, @Param("example") MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int updateByPrimaryKeySelective(MateriaPrima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbggenerated  Mon Apr 25 11:54:49 COT 2016
	 */
	int updateByPrimaryKey(MateriaPrima record);
	
	List<Map<String, Object>> SelectDataView(Map<String, Object> map);
	
	int CountDataView(Map<String, Object> map);
}