package com.colsevi.dao.inventario.map;

import com.colsevi.dao.inventario.model.MateriaPrima;
import com.colsevi.dao.inventario.model.MateriaPrimaExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MateriaPrimaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	long countByExample(MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int deleteByExample(MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int deleteByPrimaryKey(Integer lote);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int insert(MateriaPrima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int insertSelective(MateriaPrima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	List<MateriaPrima> selectByExample(MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	MateriaPrima selectByPrimaryKey(Integer lote);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int updateByExampleSelective(@Param("record") MateriaPrima record, @Param("example") MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int updateByExample(@Param("record") MateriaPrima record, @Param("example") MateriaPrimaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int updateByPrimaryKeySelective(MateriaPrima record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table materia_prima
	 * @mbg.generated  Fri Apr 28 17:42:19 COT 2017
	 */
	int updateByPrimaryKey(MateriaPrima record);

	List<Map<String, Object>> SelectDataView(Map<String, Object> map);
	
	int CountDataView(Map<String, Object> map);
}