package com.colsevi.dao.inventario.map;

import com.colsevi.dao.inventario.model.MovimientoInventario;
import com.colsevi.dao.inventario.model.MovimientoInventarioExample;
import com.colsevi.dao.inventario.model.MovimientoInventarioKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovimientoInventarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int countByExample(MovimientoInventarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int deleteByExample(MovimientoInventarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int deleteByPrimaryKey(MovimientoInventarioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int insert(MovimientoInventario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int insertSelective(MovimientoInventario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    List<MovimientoInventario> selectByExample(MovimientoInventarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    MovimientoInventario selectByPrimaryKey(MovimientoInventarioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int updateByExampleSelective(@Param("record") MovimientoInventario record, @Param("example") MovimientoInventarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int updateByExample(@Param("record") MovimientoInventario record, @Param("example") MovimientoInventarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int updateByPrimaryKeySelective(MovimientoInventario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_inventario
     *
     * @mbggenerated Tue Apr 12 16:32:27 COT 2016
     */
    int updateByPrimaryKey(MovimientoInventario record);
}