package com.colsevi.dao.inventario.map;

import com.colsevi.dao.inventario.model.MovimientoMateria;
import com.colsevi.dao.inventario.model.MovimientoMateriaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovimientoMateriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int countByExample(MovimientoMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int deleteByExample(MovimientoMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int deleteByPrimaryKey(Integer id_momivimiento_materia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int insert(MovimientoMateria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int insertSelective(MovimientoMateria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    List<MovimientoMateria> selectByExample(MovimientoMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    MovimientoMateria selectByPrimaryKey(Integer id_momivimiento_materia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int updateByExampleSelective(@Param("record") MovimientoMateria record, @Param("example") MovimientoMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int updateByExample(@Param("record") MovimientoMateria record, @Param("example") MovimientoMateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int updateByPrimaryKeySelective(MovimientoMateria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movimiento_materia
     *
     * @mbggenerated Sat Apr 23 13:02:34 COT 2016
     */
    int updateByPrimaryKey(MovimientoMateria record);
}